/**
 * Server-side loaders for firm research profiles and generated content.
 * Reads from research/firms/*.json (checked-in research) and
 * content/firms/*.json (generated by a later wave; may be absent).
 * Node fs APIs — server components / route handlers only.
 */
import fs from 'node:fs';
import path from 'node:path';
import type { FirmContent, FirmProfile } from './types';

const firmsDir = (): string => path.join(process.cwd(), 'research', 'firms');
const contentDir = (): string => path.join(process.cwd(), 'content', 'firms');

function readJsonFiles<T>(dir: string): T[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((file) => file.endsWith('.json'))
    .sort()
    .map((file) => JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8')) as T);
}

/** All researched firm profiles, sorted by id (stable docket ordering). */
export function getAllFirms(): FirmProfile[] {
  return readJsonFiles<FirmProfile>(firmsDir()).sort((a, b) => a.id.localeCompare(b.id));
}

/** Ids are slugs; anything else is rejected before touching the filesystem. */
const SAFE_ID = /^[a-z0-9-]+$/;

/** One firm profile by id, or null when unknown. */
export function getFirm(id: string): FirmProfile | null {
  if (!SAFE_ID.test(id)) return null;
  const file = path.join(firmsDir(), `${id}.json`);
  if (!fs.existsSync(file)) return null;
  return JSON.parse(fs.readFileSync(file, 'utf8')) as FirmProfile;
}

/** Generated content for one firm, or null when not yet generated. */
export function getFirmContent(id: string): FirmContent | null {
  if (!SAFE_ID.test(id)) return null;
  const file = path.join(contentDir(), `${id}.json`);
  if (!fs.existsSync(file)) return null;
  return JSON.parse(fs.readFileSync(file, 'utf8')) as FirmContent;
}

/** All generated content files present (empty array until the content wave runs). */
export function getAllFirmContent(): FirmContent[] {
  return readJsonFiles<FirmContent>(contentDir());
}

/** Editorial docket number derived from a firm's stable sort index: No. 2026-001, 002, ... */
export function docketNumber(index: number): string {
  return `No. 2026-${String(index + 1).padStart(3, '0')}`;
}
