/**
 * Local-only inquiry drafting via Ollama.
 *
 * The model receives the inquiry only through the loopback endpoint on this
 * machine. It may supply a topic, a short neutral summary, and preparation
 * prompts; the firm name, booking/deposit terms, slots, and legal language are
 * fixed by the email template and never generated by the model.
 */
import type { BaseInquiry } from '@/lib/inquiry/types';

export interface LocalEmailDraft {
  topic: string;
  summary: string;
  preparation: string[];
  source: 'local-ai' | 'fallback';
}

export interface LocalDraftInput {
  inquiry: Pick<BaseInquiry, 'message'> & { practiceFields?: Record<string, string> };
  fallbackTopic: string | null;
}

interface OllamaResponse {
  message?: { content?: string };
  response?: string;
}

type FetchLike = typeof fetch;

const MAX_TOPIC_LENGTH = 80;
const MAX_SUMMARY_LENGTH = 360;
const MAX_PREPARATION_ITEMS = 5;
const MAX_PREPARATION_LENGTH = 180;

function cleanText(value: unknown, max: number): string {
  if (typeof value !== 'string') return '';
  return value.replace(/[\r\n\t]+/g, ' ').replace(/\s+/g, ' ').trim().slice(0, max);
}

function cleanSummary(value: unknown): string {
  return cleanText(value, MAX_SUMMARY_LENGTH).replace(/^(?:further\s+)?discuss(?:ing)?\s+/i, '');
}

function fallbackTopic(value: string | null): string {
  return value ? value.replace(/-/g, ' ') : 'your inquiry';
}

/** Safe deterministic response when Ollama is off, unavailable, or malformed. */
export function fallbackLocalEmailDraft(input: LocalDraftInput): LocalEmailDraft {
  return {
    topic: fallbackTopic(input.fallbackTopic),
    summary: 'the concern you described in your contact form',
    preparation: ['A short timeline of the key events', 'The questions you want answered during the consultation'],
    source: 'fallback',
  };
}

function parseDraft(raw: string, input: LocalDraftInput): LocalEmailDraft | null {
  try {
    const parsed: unknown = JSON.parse(raw);
    if (!parsed || typeof parsed !== 'object') return null;
    const record = parsed as Record<string, unknown>;
    const topic = cleanText(record.topic, MAX_TOPIC_LENGTH);
    const summary = cleanSummary(record.summary);
    const preparation = Array.isArray(record.preparation)
      ? Array.from(
          new Set(record.preparation.map((item) => cleanText(item, MAX_PREPARATION_LENGTH)).filter(Boolean)),
        ).slice(0, MAX_PREPARATION_ITEMS)
      : [];
    if (!topic || !summary || preparation.length < 2) return null;
    return { topic, summary, preparation, source: 'local-ai' };
  } catch {
    return null;
  }
}

function promptFor(input: LocalDraftInput): string {
  const practiceFields = Object.entries(input.inquiry.practiceFields ?? {})
    .map(([name, value]) => `${name}: ${value}`)
    .join('\n');
  return [
    'Read this non-confidential law-firm contact inquiry and return JSON only.',
    'Return exactly: {"topic":"...","summary":"...","preparation":["...","...","..."]}.',
    'topic: 2-8 neutral words that accurately name the issue.',
    'summary: a neutral, lower-case phrase of at most 45 words that directly completes: "further discuss [summary]". Do not write a full sentence or use third-person labels such as "the individual".',
    'preparation: 3-5 concise, topical documents or pieces of information to bring to a consultation. Use noun phrases, not questions.',
    'Do not give legal advice, predict an outcome, make promises, add facts, request documents by email, or mention the firm, deposits, appointments, or payment.',
    'Never include sensitive data not present in the inquiry. Do not use markdown.',
    `Fallback classification (use only if the inquiry is unclear): ${fallbackTopic(input.fallbackTopic)}.`,
    `Inquiry: ${input.inquiry.message}`,
    ...(practiceFields ? [`Additional form answers:\n${practiceFields}`] : []),
  ].join('\n\n');
}

/**
 * Calls the local Ollama server. Any error intentionally becomes a safe
 * fallback so an unavailable local model cannot prevent firm intake delivery.
 */
export async function generateLocalEmailDraft(
  input: LocalDraftInput,
  env: Record<string, string | undefined> = process.env,
  fetchImpl: FetchLike = fetch,
): Promise<LocalEmailDraft> {
  if (env.AI_PROVIDER && env.AI_PROVIDER !== 'ollama') return fallbackLocalEmailDraft(input);

  const baseUrl = (env.OLLAMA_BASE_URL || 'http://127.0.0.1:11434').replace(/\/+$/, '');
  const model = env.OLLAMA_MODEL || 'qwen2.5:7b';
  const timeoutMs = Number(env.OLLAMA_TIMEOUT_MS || 45_000);
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), Number.isFinite(timeoutMs) ? timeoutMs : 45_000);

  try {
    const response = await fetchImpl(`${baseUrl}/api/chat`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      signal: controller.signal,
      body: JSON.stringify({
        model,
        stream: false,
        format: 'json',
        options: { temperature: 0.1, num_predict: 320 },
        messages: [
          {
            role: 'system',
            content:
              'You are a careful law-firm intake writing assistant. Output only valid JSON matching the requested schema.',
          },
          { role: 'user', content: promptFor(input) },
        ],
      }),
    });
    if (!response.ok) return fallbackLocalEmailDraft(input);
    const payload = (await response.json()) as OllamaResponse;
    return parseDraft(payload.message?.content ?? payload.response ?? '', input) ?? fallbackLocalEmailDraft(input);
  } catch {
    return fallbackLocalEmailDraft(input);
  } finally {
    clearTimeout(timer);
  }
}
